fixed RuntimeError
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Float for the source.
- changed CONST and label to type long